name: Run Tests
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.7.6
          poetry_version: 1.0.3
          working_directory: . # Optional, defaults to '.'
          args: install
      - name: Run pytest
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.7.6
          poetry_version: 1.0.3
          working_directory: .
          args: run python -m pytest --cov=flitch --cov-branch --cov-fail-under=100 tests/
