name: CI

on: [push]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Code Quality
        run: |
          poetry run black . --check
          poetry run isort -rc --check-only .

      - name: Test with pytest
        run: poetry run pytest --cov flitch

      - name: Build Docs
        if: github.ref == 'refs/heads/feature/pdoc3'
        run: poetry run pdoc3 --html flitch

      - name: Deploy Docs
        if: github.ref == 'refs/heads/feature/pdoc3'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: html/flitch # The folder the action should deploy.
          COMMIT_MESSAGE: 🚀 [CI] Auto updating GH Pages
